name: Sync LICENSE from Legal Engine

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update-legal]

permissions:
  contents: write

jobs:
  sync-license:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout main repo
      - name: Checkout Repo
        uses: actions/checkout@v5

      # 2. Checkout legal-engine
      - name: Get Legal Engine
        uses: actions/checkout@v5
        with:
          repository: Adel-EUAI/legal-engine
          path: legal-engine
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      # 3. Copy LICENSE based on config
      - name: Process and Copy LICENSE
        run: |
                CONFIG_PATH="./legal.config.json"
                FILE=$(jq -r '.legal_files[0]' "$CONFIG_PATH")
                APP_NAME=$(jq -r '.app_name' "$CONFIG_PATH")
                SOURCE_PATH="legal-engine/src/$FILE"

                if [ ! -f "$SOURCE_PATH" ]; then
                  echo "❌ File not found at: $SOURCE_PATH"
                  exit 1
                fi

                # خواندن فایل، جایگزینی تگ و ذخیره در ریشه
                sed "s/{{APP_NAME}}/$APP_NAME/g" "$SOURCE_PATH" > ./LICENSE.md
                
                echo "✅ Processed and generated LICENSE.md with name: $APP_NAME"

      # 4. Commit & Push if changed
      - name: Commit LICENSE
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          if git diff --quiet LICENSE.md; then
            echo "No changes"
          else
            git add LICENSE.md
            git commit -m "chore: sync LICENSE.md from legal-engine"
            git push origin main
          fi
